http_base_url: http://intrepid.local

pid_file_location: ""

services:
    kismet:
        system_ctl_name: kismet.service
        type: systemd
        description: Kismet
        link: http://intrepid.local:2501
        require_sdr: false
    openwebex:
        type: docker
        container_name: owrx-mbe
        description: "Openwebex+"
        link: "http://intrepid.local:8073"
        default_sdr: '77771111153705700'
        selected_sdr: '77771111153705700'
        require_sdr: true
        multi_sdr: false
    intercept:
        type: docker
        container_name: intercept
        description: "intercept"
        link: "http://intrepid.local:5050"
        require_sdr: true
        multi_sdr: true
        default_sdr: null
    pagermon_server:
        type: docker
        container_name: pagermon
        description: Pagermon Server
        cmd_line: ""
        working_dir: "/opt/pagermon"
        require_sdr: false
        link: "http://intrepid.local:3000/"
    pagermon_client1:
        type: cli
        description: Pagermon Client
        cmd_line: "/opt/pagermon/client/reader_alt.sh 1 152.592M"
        working_dir: /opt/pagermon/client
        require_sdr: true
        multi_sdr: false
        freq_input: "152.592M"
        default_sdr: null
        link: null
    pagermon_client2:
        type: cli
        description: Pagermon Client
        cmd_line: "/opt/signals_box_ctl/pagermon_client.sh 2 929.612M"
        working_dir: /opt/pagermon/client
        default_sdr: null
        require_sdr: true
        multi_sdr: false
        freq_input: "929.612M"
        link: null

buttons:
  refresh_page:
    name: "refresh_page" 
    text: "Refresh Page"
    html_command: "onClick=\"window.location.reload();\""
  reload_config:
    name: "reload_config" 
    text: "Reload Config"
    html_command: "type=\"submit\""
  svc_restart:
    name: "svc_restart" 
    text: "Restart Service_ctl"
    html_command: "type=\"submit\""
    cli_command: ["/usr/bin/systemctl", "restart", "service_ctl.service"]
  shutdown:
    name: "shutdown" 
    text: "Shutdown"
    html_command: "type=\"submit\""
    cli_command: ["/usr/sbin/shutdown", "now"]
  reboot:
    name: "reboot" 
    text: "Reboot"
    html_command: "type=\"submit\""
    cli_command: ["/usr/sbin/reboot"]

links:
  - id: vnc
    url: "vnc://intredpid.local:5901"
    name: VNC Access
  # - id: rdp
  #   url: "rdp://signals.local"
  #   name: RDP Access
