http_base_url: http://signals.local

pid_file_location: ""

services:
    gps:
        system_ctl_name: gpsd.service
        type: systemd
        autostart: true
        require_sdr: false
        multi_sdr: false
    kismet:
        system_ctl_name: kismet.service
        type: systemd
        description: Kismet
        link: http://intrepid.local:2501
        autostart: false
        require_sdr: false
        multi_sdr: false
    openwebex:
        type: docker
        container_name: owrx-mbe
        description: "Openwebex+"
        link: "http://intrepid.local:8073"
        autostart: false
        default_sdr: '77771111153705700'
        require_sdr: true
        multi_sdr: false
    intercept:
        type: docker
        container_name: intercept
        description: "intercept"
        link: "http://intrepid.local:5050"
        autostart: false
        require_sdr: true
        default_sdr: null
        multi_sdr: true
    pagermon_server:
        type: docker
        container_name: pagermon
        description: Pagermon Server
        cmd_line: ""
        working_dir: "/opt/pagermon"
        autostart: false
        require_sdr: false
        multi_sdr: false
        link: "http://intrepid.local:3000/"
    pagermon_client1:
        type: cli
        description: Pagermon Client
        cmd_line: "/opt/pagermon/client/reader_alt.sh 1 152.592M"
        working_dir: /opt/pagermon/client
        autostart: false
        freq_input: "152.592M"
        require_sdr: true
        default_sdr: null
        link: null
        multi_sdr: false
    pagermon_client2:
        type: cli
        description: Pagermon Client
        cmd_line: "/opt/signals_box_ctl/pagermon_client.sh 2 929.612M"
        working_dir: /opt/pagermon/client
        autostart: false
        default_sdr: null
        require_sdr: true
        freq_input: "929.612M"
        link: null
        multi_sdr: false

buttons:
  refresh_page:
    name: "refresh_page" 
    text: "Refresh Page"
    html_command: "onClick=\"window.location.reload();\""
  reload_config:
    name: "reload_config" 
    text: "Reload Config"
    html_command: "type=\"submit\""
  svc_restart:
    name: "svc_restart" 
    text: "Restart Service_ctl"
    html_command: "type=\"submit\""
    cli_command: ["/usr/bin/systemctl", "restart", "service_ctl.service"]
  shutdown:
    name: "shutdown" 
    text: "Shutdown"
    html_command: "type=\"submit\""
    cli_command: ["/usr/sbin/shutdown", "now"]
  reboot:
    name: "reboot" 
    text: "Reboot"
    html_command: "type=\"submit\""
    cli_command: ["/usr/sbin/reboot"]

links:
  - id: vnc
    url: "vnc://intredpid.local:5901"
    name: VNC Access
  - id: radioreference
    url: "https://www.radioreference.com/"
    name: Radioreference
  - id: homescanner
    url: "https://scanner.home.the-collective.net/"
    name: "Home Rdio Scanner" 
  - id: sigidwiki
    url: "https://www.sigidwiki.com/"
    name: "SigIdWiki"
      # - id: rdp
  #   url: "rdp://signals.local"
  #   name: RDP Access
